name: "TimSchreiber.com"
baseurl: "https://timschreiber.com"
permalink: /:categories/:year/:month/:day/:title/
title: "Timothy P. Schreiber"
image: "timothy-p-schreiber-3.jpg"
image_width: 1280
image_height: 683
